version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - docker.env
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres
    env_file:
      - docker.env
    ports:
      - "5431:5432"
    volumes:
      - ./data:/var/lib/post